# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleOfPods' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SampleOfPods
pod 'Reachability',  '~> 3.0.0'
pod 'Nimbus'
pod 'BlocksKit'

end
