# Uncomment the next line to define a global platform for your project
# platform :ios, ‘6.1’

target 'GHUnitTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GHUnitIOS', '~> 0.6.1’
  # Pods for GHUnitTest

end

target 'janken' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for janken

end

target 'jankenKIF' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'KIF'
  # Pods for jankenKIF

end

target 'KiwiTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Kiwi'
  # Pods for KiwiTest

end
